name: Reusable workflow

on:
  workflow_call:

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        uses: andstor/file-existence-action@v1
        with:
          files: "gradle.lockfile"
          allow_failure: true

      - name: Backstage Entity Validator
        uses: RoadieHQ/backstage-entity-validator@v0.3.2
        with:
          path: '.backstage/catalog-info.yaml'

      - name: Check Dependencies
        if: "!contains(github.event.pull_request.labels.*.name, 'skip-check-dependencies')"
        uses: paypay/match-lines-action@releases/v1
        with:
          target_file: 'gradle.lockfile'
          matcher: |
            spring-boot-starter:[0-1]
            spring-boot-starter:2\.[0-3]
            yaml:snakeyaml:1
          allow_failure: true
